#!/usr/bin/env python

import os
from faster_whisper import download_model

from predict import SUPPORTED_MODEL_NAMES

os.makedirs("whisper-cache", exist_ok=True)

for model in SUPPORTED_MODEL_NAMES:
    print(f"Downloading {model}...")

    download_model(model, cache_dir="whisper-cache")
